### ISSUE TITLE
Is there a Bill of Materials for the parts used in this repo?

### ISSUE THREAD

**Issue by octarinesun** [9R/replicazeron#1]
Hello,

Thank you for the great work here! I really love the OLED idea. I'd love it if there were links to the additional pieces you used to build off of the base project you linked in the readme.

For example, the OLED and the MCU you used.

Thanks again!

**Comment by 9R** [comment]
Thank you for your interest in the project.

I have updated the README a bit and have added a BOM.

Unfortunately I will have to disappoint you concerning a list of links to additional parts. On one hand I do not want to maintain and update such a list but the main reason is that I do not want to add (affiliate) links to this repo that favor a single platform.

That said: All parts I used are pretty standard maker supplies and it should be easy to source them from the vendor of your choice.

If you have further questions feel free to ask

**Comment by alexuadler** [comment]
That's perfect (and fast!), thanks!

**Comment by alexuadler** [comment]
I believe in adding the BoM the source link to the original guide is broken. I see the url in the reader source code but a broken image tag on the resume itself

**Comment by 9R** [comment]
Ah, thanks for letting me know. There was a typo that caused github to try to show an image instead of a link. Fixed

**Comment by 9R** [comment]
Closing the issue. Please reopen if anything else is still missing
