### ISSUE TITLE
Does it support xinput?

### ISSUE THREAD

**Issue by rp1231** [9R/replicazeron#2]
Does this support xinput?
Thanks

**Comment by 9R** [comment]
The code in my QMK pull request for this devices currently only uses the analog stick to send keyboard key presses. But the only reason for this is, that I use it with a mouse in my right hand and all software/games I tested it with did only support input from a mouse + keyboard or from a controller, not from mouse + controller.
That said, QMK can operate as a joystick, see the [QMK documentation](https://docs.qmk.fm/keycodes) for more details.
To get this device to send controller key presses you just need to map the desired key codes in via. If you want the analog stick to act as joystick towards the OS the firmware needs some minor adjustments.
Check the [firmware repo](https://github.com/9R/qmk_firmware/tree/replicazeron/keyboards/handwired/replicazeron) for detail. Pull requests are always welcome.
